### ISSUE TITLE
Image direction

### ISSUE THREAD

**Issue by m-pilia** [simeks/stk#9]
Correct me if I am wrong, but I think STK does not handle image direction, right? Because the NRRD format supports image direction metadata (while I think VTK structured point does not). Now, it is quite unusual to have images with non-canonical axis directions, but if that happened then the results may be wrong if images with different directions were mixed. Handling directions could be annoying, but I was thinking for the moment we could at least throw an error in `stk::nrrd::read` if the image to be loaded from file has non-canonical direction.

**Comment by simeks** [comment]
You're right, I've been pushing that for a while now as only thinking about it gives me a headache. This is relevant for both NRRD and nifti. Having some error messages is a good idea, there are some assertions for weird nifti configurations but nothing for NRRD I think.

I'm thinking about extending the support for metadata in volumes. Maybe have some key-value storage to at least make them available. Now they're completely discarded during read.
